### ISSUE TITLE
[UI] Better error handling for timeslot

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#23]
Currently, the error given is ambiguous... can either be a wrong URL or an empty link space
![image](https://user-images.githubusercontent.com/41845017/175974454-be144092-4613-44e5-94d2-6c420c5d1b32.png)

Wonder if you can:
- Be specific: find out exactly what is the error (should be doable), and give the error as just that. If there are two errors -> give two errors. If there's only one error -> give just that error. If no error -> don't give error
- Auto remove incorrect URL
- Auto remove empty input

**Comment by wilsonngja** [comment]
![image](https://user-images.githubusercontent.com/31720838/176728007-bd7fe80c-937b-431c-ad93-bb248494434b.png)
![image](https://user-images.githubusercontent.com/31720838/176728056-d14c58f3-3124-496d-852f-3313cf5ea3eb.png)
![image](https://user-images.githubusercontent.com/31720838/176728095-f9d1bf0e-fe71-418d-a664-08898d3260ee.png)
![image](https://user-images.githubusercontent.com/31720838/176728242-352be4e8-808e-41f5-99f7-eb49147391ee.png)

I've made the changes as shown above. 
If there is no links provided, there will be an error shown because it will just show everyday 0800 to 2359.
