### ISSUE TITLE
[UI] Venue information presented not as helpful for users

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#32]
Given the current display of venues when searching, the code name of the locations/rooms are not easily understandable. This means users may need to click on a room button to find out where this room is located. This means they need to do so manually a number of times just to find out which room is a suitable one.

Ideally, it should be easy to find out where this room is and some categorization/grouping of the rooms may be useful. Referencing the venue UI in NUSMODS, you get to see the map on the same page and immediately when you click on a button. Rooms are also organized by Alphabetical order

**Comment by wilsonngja** [comment]
![image](https://user-images.githubusercontent.com/31720838/178681248-817471db-e99e-46ac-8785-b52b923af666.png)

Changes has been made to display the venues within the website. 
However, we are not able to categorize the rooms such as by faculties as the venue info provided is just the venue and the timing there is lesson.

What we have done so far is sorted the rooms by alphabetical order and believed that it should be kind of sorted by their location (Since the faculties block are somewhat similar in name).
